"""Builds the GridTokenReader Node-RED tab.

Usage: python3 build-flow.py <influx_config_id|new> <org> <bucket> > flow.json

With influx_config_id "new", an InfluxDB v2 config node (http://127.0.0.1:8086) is
included; set its token in the Node-RED editor after importing.

Pipeline:
  POST /gridtoken/ingest (JPEG, behind the nginx token gate, see docs/NGINX.md)
    -> save frame -> recogniser (Python, exec) -> plausibility -> InfluxDB
  POST /gridtoken/reading (JSON {"kwh": ...}) -> InfluxDB pln_prepaid

Tab environment variables (edit on the tab):
  GRIDTOKEN_FRAMES         frame directory (default /var/lib/gridtoken/frames)
  GRIDTOKEN_RECOGNISER     directory with gridtoken_recognise.py and profiles/<device>.json
  GRIDTOKEN_PUBLISH        "true" = accepted camera readings go to pln_prepaid;
                           otherwise shadow mode (only gridtoken_recognition is written)
  GRIDTOKEN_MAX_KW         supply limit for the plausibility check (25 A x 230 V = 5.75)
  GRIDTOKEN_TOPUP_MIN_KWH  smallest rise treated as a token top-up
  GRIDTOKEN_TELEGRAM_CHAT  chat id for alerts (empty = no alerts); the "Telegram"
                           http request node needs your bot URL
"""
import json
import sys

INFLUX_CFG, ORG, BUCKET = sys.argv[1], sys.argv[2], sys.argv[3]
Z = "gtr0tab00000001"
FRAMES = "/var/lib/gridtoken/frames"
RECOGNISER = "/opt/gridtoken-recogniser"


def fn(id_, name, code, x, y, wires, outputs=None):
    return {
        "id": id_, "type": "function", "z": Z, "name": name, "func": code,
        "outputs": outputs or len(wires), "timeout": 0, "noerr": 0,
        "initialize": "", "finalize": "", "libs": [], "x": x, "y": y, "wires": wires,
    }


VALIDATE_FRAME = r"""// Device identity comes from nginx (token -> X-Device-Id); never from the body.
const dev = String(msg.req.headers['x-device-id'] || '').replace(/[^a-z0-9-]/gi, '');
const buf = msg.payload;
const isJpeg = Buffer.isBuffer(buf) && buf.length > 1000 && buf[0] === 0xFF && buf[1] === 0xD8;
const resp = { req: msg.req, res: msg.res, statusCode: 204, payload: '' };
if (!dev || !isJpeg) {
    resp.statusCode = 400;
    resp.payload = 'expected image/jpeg from a known device';
    node.warn(`rejected frame from '${dev}' (${Buffer.isBuffer(buf) ? buf.length : typeof buf})`);
    return [null, resp, null];
}
const parse = h => { try { return JSON.parse(msg.req.headers[h] || '{}'); } catch (e) { return {}; } };
const status = parse('x-device-status');
const capture = parse('x-capture');   // {"light": "backlight"|"led", "lcd_luma": n}
const frame = { device: dev, ts: Date.now(), image: buf, firmware: msg.req.headers['x-firmware'] || null, status, capture };

const fields = { bytes: buf.length };
for (const k of ['rssi', 'heap', 'psram', 'uptime_s']) {
    if (Number.isFinite(status[k])) fields[k] = status[k];
}
if (Number.isFinite(capture.lcd_luma)) fields.lcd_luma = capture.lcd_luma;
if (capture.light) fields.led = capture.light === 'led' ? 1 : 0;
const tags = { device: dev };
if (frame.firmware) tags.firmware = String(frame.firmware);
const metrics = { payload: [{ measurement: 'gridtoken_ingest', fields, tags }] };

node.status({ fill: 'green', shape: 'dot', text: `${dev} ${buf.length} B ${capture.light || ''} ${new Date().toLocaleTimeString()}` });
return [frame, resp, metrics];
"""

FRAME_PATHS = r"""// /var/lib/gridtoken/frames/<device>/<YYYY-MM-DD>/<HHMMSS>.jpg (+ latest.jpg).
// Only the dated copy is handed on to the recogniser (after it is written).
const dir = env.get('GRIDTOKEN_FRAMES') || '""" + FRAMES + r"""';
const d = new Date(msg.ts);
const p2 = n => String(n).padStart(2, '0');
const day = `${d.getFullYear()}-${p2(d.getMonth() + 1)}-${p2(d.getDate())}`;
const t = `${p2(d.getHours())}${p2(d.getMinutes())}${p2(d.getSeconds())}`;
const meta = { device: msg.device, ts: msg.ts, capture: msg.capture };
return [[
    { ...meta, filename: `${dir}/${msg.device}/${day}/${t}.jpg`, payload: msg.image, recognise: true },
    { ...meta, filename: `${dir}/${msg.device}/latest.jpg`, payload: msg.image },
]];
"""

RECOGNISE_ARGS = r"""// Runs after the dated frame is on disk: build the recogniser's arguments.
if (!msg.recognise) return null;
const base = env.get('GRIDTOKEN_RECOGNISER') || '""" + RECOGNISER + r"""';
// device and filename are generated by this flow ([a-z0-9-], digits): safe to pass to the shell.
msg.frame = msg.filename;
msg.payload = `--profile ${base}/profiles/${msg.device}.json ${msg.filename}`;
return msg;
"""

EVALUATE = r"""// Plausibility gate for camera readings. The balance only goes down, at most
// as fast as the supply allows, and only jumps up on a token top-up (confirmed
// by the next frame). Everything is logged to gridtoken_recognition; accepted
// readings go to pln_prepaid only when GRIDTOKEN_PUBLISH is "true".
let r;
try { r = JSON.parse(msg.payload); } catch (e) { r = { ok: false, reason: 'bad recogniser output' }; }
const dev = msg.device;
const now = msg.ts || Date.now();
const maxKw = Number(env.get('GRIDTOKEN_MAX_KW') || 5.75);
const topupMin = Number(env.get('GRIDTOKEN_TOPUP_MIN_KWH') || 5);
const publish = String(env.get('GRIDTOKEN_PUBLISH')) === 'true';
const key = 'gt_state_' + dev;
const st = flow.get(key) || { last: null, pending: null, rejects: null };
const same = (a, b) => Math.abs(a - b) < 0.015;
let verdict = 'unreadable', reason = r.reason || null, topup = null;

if (r.ok && typeof r.kwh === 'number') {
    const k = r.kwh;
    const accept = why => { st.last = { kwh: k, ts: now }; st.pending = null; st.rejects = null; verdict = 'accepted'; reason = why; };
    const hold = why => { st.pending = { kwh: k, ts: now }; verdict = 'pending'; reason = why; };
    if (!st.last) {
        if (st.pending && same(st.pending.kwh, k)) accept('baseline');
        else hold('baseline: waiting for a confirming frame');
    } else {
        const hours = Math.max(0, (now - st.last.ts) / 3.6e6);
        const drop = st.last.kwh - k;
        if (drop >= -0.005 && drop <= maxKw * hours + 0.02) {
            accept(null);
        } else if (-drop >= topupMin) {
            if (st.pending && same(st.pending.kwh, k)) { topup = +(k - st.last.kwh).toFixed(2); accept('topup'); }
            else hold('top-up: waiting for a confirming frame');
        } else {
            verdict = 'rejected';
            reason = drop > 0 ? `drop ${drop.toFixed(2)} kWh in ${hours.toFixed(2)} h exceeds ${maxKw} kW`
                              : `rise ${(-drop).toFixed(2)} kWh is too small for a top-up`;
            // A wrong baseline must not lock us out: 6 identical rejected reads (~30 min) re-anchor.
            st.rejects = st.rejects && same(st.rejects.kwh, k) ? { kwh: k, n: st.rejects.n + 1 } : { kwh: k, n: 1 };
            if (st.rejects.n >= 6) accept('re-anchored after 6 identical reads');
        }
    }
}
flow.set(key, st);

const fields = { ok: r.ok ? 1 : 0, accepted: verdict === 'accepted' ? 1 : 0, verdict, confidence: Number(r.confidence) || 0 };
if (typeof r.kwh === 'number') fields.kwh = r.kwh;
if (topup !== null) fields.topup_kwh = topup;
if (reason) fields.reason = String(reason);
if (r.digits) fields.digits = String(r.digits);
if (r.code) fields.code = String(r.code);
if (msg.capture && msg.capture.light) fields.led = msg.capture.light === 'led' ? 1 : 0;
const shadow = { payload: [{ measurement: 'gridtoken_recognition', fields, tags: { device: dev } }] };

node.status({ fill: verdict === 'accepted' ? 'green' : verdict === 'pending' ? 'yellow' : 'red', shape: 'dot',
              text: `${verdict}${typeof r.kwh === 'number' ? ' ' + r.kwh + ' kWh' : ''}${reason ? ' (' + reason + ')' : ''}${publish ? '' : ' [shadow]'}` });

const reading = verdict === 'accepted' && publish
    ? { device: dev, kwh: r.kwh, confidence: Number(r.confidence) || 0, source: 'camera' } : null;
const events = [];
if (topup !== null && publish) events.push({ kind: 'topup', device: dev, topup, kwh: r.kwh });
return [shadow, reading, events.length ? events : null];
"""

BACKLIGHT_WATCH = r"""// Backlight watch: the SMI-810 keeps its LCD backlight off after a power cut
// until a key is pressed; the camera then falls back to its LED (light=led).
// Alert once when that starts and once when it is back.
const dev = msg.device;
const light = msg.capture && msg.capture.light;
if (!light) return null;
const key = 'gt_backlight_' + dev;
const prev = flow.get(key) || 'backlight';
flow.set(key, light);
if (light === prev) return null;
return { kind: light === 'led' ? 'backlight_off' : 'backlight_on', device: dev, luma: msg.capture.lcd_luma };
"""

TELEGRAM_TEXT = r"""// Telegram sendMessage query (GET, payload -> query string), like the other tabs.
const chat = env.get('GRIDTOKEN_TELEGRAM_CHAT');
if (!chat) return null;
const text = {
    backlight_off: `💡 Meter backlight is OFF (${msg.device}). Press any key on the PLN meter so the camera can keep reading it.`,
    backlight_on: `✅ Meter backlight is back on (${msg.device}).`,
    topup: `🔌 PLN token top-up detected: +${msg.topup} kWh, balance now ${msg.kwh} kWh.`,
}[msg.kind];
if (!text) return null;
return { payload: { chat_id: chat, text } };
"""

TO_INFLUX = r"""// pln_prepaid: remaining prepaid balance in kWh as read off the meter.
// Grafana extrapolates between readings with a grid power integral (deploy/grafana-available-credit.flux).
flow.set('lastReading', { device: msg.device, kwh: msg.kwh, source: msg.source, ts: Date.now() });
node.status({ fill: 'blue', shape: 'dot', text: `${msg.kwh} kWh (${msg.source}) ${new Date().toLocaleString()}` });
return { payload: [{
    measurement: 'pln_prepaid',
    fields: { kwh: msg.kwh, confidence: msg.confidence },
    tags: { device: msg.device, source: msg.source },
}] };
"""

VALIDATE_READING = r"""// POST /gridtoken/reading  {"kwh": 59.23, "confidence": 0.98}
// For manual anchors (token 'manual') and, later, on-device recognition.
// Device identity comes from nginx.
const dev = String(msg.req.headers['x-device-id'] || '').replace(/[^a-z0-9-]/gi, '');
const p = (typeof msg.payload === 'object' && msg.payload) || {};
const kwh = Number(p.kwh);
const resp = { req: msg.req, res: msg.res, statusCode: 204, payload: '' };
if (!dev || !Number.isFinite(kwh) || kwh < 0 || kwh > 100000) {
    resp.statusCode = 400;
    resp.payload = 'expected JSON {"kwh": <number>}';
    return [null, resp];
}
const confidence = p.confidence == null ? 1 : Math.max(0, Math.min(1, Number(p.confidence) || 0));
// A manual reading re-anchors: reset every camera's plausibility baseline.
if (dev === 'manual') flow.keys().filter(k => k.startsWith('gt_state_')).forEach(k => flow.set(k, undefined));
return [{ device: dev, kwh, confidence, source: dev === 'manual' ? 'manual' : 'camera' }, resp];
"""

nodes = [
    {"id": Z, "type": "tab", "label": "GridTokenReader", "disabled": False,
     "info": "Prepaid meter camera (github.com/afardana/GridTokenReader).\n\n"
             "Endpoints sit behind the nginx token gate (docs/NGINX.md): a per-device bearer token is "
             "checked there and mapped to X-Device-Id, and nginx adds httpNodeAuth. Frames: " + FRAMES +
             " (30-day retention). InfluxDB: gridtoken_ingest (device health), gridtoken_recognition "
             "(every recogniser result + plausibility verdict), pln_prepaid (kWh readings).\n\n"
             "Shadow mode until GRIDTOKEN_PUBLISH=true (tab env).",
     "env": [
         {"name": "GRIDTOKEN_FRAMES", "value": FRAMES, "type": "str"},
         {"name": "GRIDTOKEN_RECOGNISER", "value": RECOGNISER, "type": "str"},
         {"name": "GRIDTOKEN_PUBLISH", "value": "false", "type": "str"},
         {"name": "GRIDTOKEN_MAX_KW", "value": "5.75", "type": "str"},
         {"name": "GRIDTOKEN_TOPUP_MIN_KWH", "value": "5", "type": "str"},
         {"name": "GRIDTOKEN_TELEGRAM_CHAT", "value": "", "type": "str"},
     ]},
    {"id": "gtr0cmt00000001", "type": "comment", "z": Z,
     "name": "Frames: POST /gridtoken/ingest (JPEG)  ·  Readings: POST /gridtoken/reading (JSON)",
     "info": "", "x": 330, "y": 40, "wires": []},

    # --- frames
    {"id": "gtr0in000000001", "type": "http in", "z": Z, "name": "POST /gridtoken/ingest",
     "url": "/gridtoken/ingest", "method": "post", "upload": False, "swaggerDoc": "",
     "x": 170, "y": 120, "wires": [["gtr0fnvalframe1"]]},
    fn("gtr0fnvalframe1", "validate frame", VALIDATE_FRAME, 400, 120,
       [["gtr0fnpaths0001", "gtr0fnbacklite1"], ["gtr0resp0000001"], ["gtr0influx00001"]]),
    {"id": "gtr0resp0000001", "type": "http response", "z": Z, "name": "ack",
     "statusCode": "", "headers": {}, "x": 630, "y": 240, "wires": []},
    fn("gtr0fnpaths0001", "frame paths", FRAME_PATHS, 640, 80, [["gtr0file0000001"]]),
    {"id": "gtr0file0000001", "type": "file", "z": Z, "name": "save frame",
     "filename": "filename", "filenameType": "msg", "appendNewline": False,
     "createDir": True, "overwriteFile": "true", "encoding": "none",
     "x": 830, "y": 80, "wires": [["gtr0fnrecog0001"]]},
    fn("gtr0fnrecog0001", "recogniser args", RECOGNISE_ARGS, 1020, 80, [["gtr0execrecog01"]]),
    {"id": "gtr0execrecog01", "type": "exec", "z": Z,
     "command": "python3 " + RECOGNISER + "/gridtoken_recognise.py",
     "addpay": "payload", "append": "", "useSpawn": "false", "timer": "60", "winHide": False,
     "oldrc": False, "name": "7-segment recogniser", "x": 1240, "y": 80,
     "wires": [["gtr0fnevaluate1"], [], []]},
    fn("gtr0fnevaluate1", "plausibility", EVALUATE, 1260, 160,
       [["gtr0influx00001"], ["gtr0fntoinflux1"], ["gtr0fntelegram1"]]),
    fn("gtr0fnbacklite1", "backlight watch", BACKLIGHT_WATCH, 640, 160, [["gtr0fntelegram1"]]),
    fn("gtr0fntelegram1", "alert text", TELEGRAM_TEXT, 1260, 300, [["gtr0telegram001"]]),
    {"id": "gtr0telegram001", "type": "http request", "z": Z, "name": "Telegram",
     "method": "GET", "ret": "txt", "paytoqs": "query",
     "url": "https://api.telegram.org/bot<YOUR_BOT_TOKEN>/sendMessage",
     "tls": "", "persist": False, "proxy": "", "insecureHTTPParser": False, "authType": "",
     "senderr": False, "headers": [], "x": 1470, "y": 300, "wires": [[]]},

    # --- readings
    {"id": "gtr0in000000002", "type": "http in", "z": Z, "name": "POST /gridtoken/reading",
     "url": "/gridtoken/reading", "method": "post", "upload": False, "swaggerDoc": "",
     "x": 170, "y": 340, "wires": [["gtr0fnvalread01"]]},
    fn("gtr0fnvalread01", "validate reading", VALIDATE_READING, 400, 340,
       [["gtr0fntoinflux1"], ["gtr0resp0000001"]]),
    fn("gtr0fntoinflux1", "pln_prepaid point", TO_INFLUX, 1480, 200, [["gtr0influx00001"]]),
    {"id": "gtr0influx00001", "type": "influxdb batch", "z": Z, "influxdb": INFLUX_CFG,
     "precision": "", "retentionPolicy": "", "name": "InfluxDB (local)", "database": "",
     "precisionV18FluxV20": "ms", "retentionPolicyV18Flux": "", "org": ORG, "bucket": BUCKET,
     "x": 1700, "y": 200, "wires": []},

    # --- housekeeping
    {"id": "gtr0inject00001", "type": "inject", "z": Z, "name": "daily 03:30",
     "props": [{"p": "payload"}], "repeat": "", "crontab": "30 03 * * *", "once": False,
     "onceDelay": 0.1, "topic": "", "payload": "", "payloadType": "date",
     "x": 170, "y": 440, "wires": [["gtr0exec0000001"]]},
    {"id": "gtr0exec0000001", "type": "exec", "z": Z,
     "command": "find " + FRAMES + " -type f -name '*.jpg' ! -name latest.jpg -mtime +30 -delete; "
                "find " + FRAMES + " -mindepth 2 -type d -empty -delete",
     "addpay": "", "append": "", "useSpawn": "false", "timer": "120", "winHide": False,
     "oldrc": False, "name": "prune frames > 30 days", "x": 420, "y": 440,
     "wires": [[], [], []]},
]

if INFLUX_CFG == "new":
    for n in nodes:
        if n.get("influxdb") == "new":
            n["influxdb"] = "gtr0influxcfg01"
    nodes.append({"id": "gtr0influxcfg01", "type": "influxdb", "hostname": "127.0.0.1", "port": "8086",
                  "protocol": "http", "database": "", "name": "InfluxDB (set token)", "usetls": False,
                  "tls": "", "influxdbVersion": "2.0", "url": "http://127.0.0.1:8086", "timeout": "",
                  "rejectUnauthorized": True})

json.dump(nodes, sys.stdout, indent=4, ensure_ascii=False)
